const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const {WebSocketServer,WebSocket}=require("ws");
const {Pool}=require("pg");
const PORT=Number(process.env.PORT||3101),ASSET_PORT=Number(process.env.ASSET_PORT||3102);
const ADMIN_TOKEN=String(process.env.ADMIN_TOKEN||""),PRIORITY_PRICE=String(process.env.PRIORITY_PRICE||"R$ 5,00"),PRIORITY_PAYMENT_LINK=String(process.env.PRIORITY_PAYMENT_LINK||""),DATABASE_URL=String(process.env.DATABASE_URL||"");
const ROOT=__dirname,STATE_FILE=path.join(ROOT,"data","state-v6.json");try{fs.mkdirSync(path.dirname(STATE_FILE),{recursive:true})}catch(e){}
const MAX_HISTORY=120,MAX_EVENTS=120,RACE_TARGET=30,CHAT_INTERVAL=650,MINE_INTERVAL=95,MAX_MUSIC_QUEUE=60;
const clients=new Map(),messages=[],rooms=new Map(),musicQueue=[];let currentSong=null,pool=null,dbReady=false,saveTimer=null;
const leaderboards=new Map([["mineracao",[]],["memoria",[]],["creeper",[]],["crafting",[]],["quiz",[]],["corrida",[]]]);
const interactions={visits:0,pageViews:{},reactions:{hype:0,heart:0,crown:0,surprise:0},chatMessages:0,musicRequests:0,musicVotes:0,gamesPlayed:0,overlayEvents:0,lastEvents:[]};
const profiles={};
function clean(v,max=120){return String(v??"").replace(/[\u0000-\u001F\u007F]/g," ").trim().slice(0,max)}
function now(){return Date.now()}
function send(ws,d){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(d))}
function broadcast(d,filter=()=>true){const p=JSON.stringify(d);for(const[ws,i]of clients)if(ws.readyState===WebSocket.OPEN&&filter(i,ws))ws.send(p)}
function presence(){broadcast({type:"presence",online:clients.size})}
function youtubeId(url=""){const m=String(url).match(/(?:youtu\.be\/|(?:www\.|m\.|music\.)?youtube\.com\/(?:watch\?[^#]*v=|shorts\/|embed\/))([\w-]{6,})/i);return m?m[1]:""}
function safeName(n){return clean(n,20)||("Minerador-"+crypto.randomBytes(2).toString("hex").toUpperCase())}
function profileKey(n){return safeName(n).toLowerCase()}
function ensureProfile(n){const k=profileKey(n);if(!profiles[k])profiles[k]={name:safeName(n),xp:0,level:1,stats:{chat:0,games:0,reactions:0,music:0,votes:0,wins:0},lastSeen:new Date().toISOString()};profiles[k].name=safeName(n);profiles[k].lastSeen=new Date().toISOString();return profiles[k]}
function levelFor(xp){return Math.max(1,Math.floor(Math.sqrt(Math.max(0,xp)/28))+1)}
function missions(p){const s=p?.stats||{};return[{id:"react",title:"Reagir 3 vezes",now:Math.min(3,s.reactions||0),target:3},{id:"game",title:"Jogar 1 minigame",now:Math.min(1,s.games||0),target:1},{id:"social",title:"Enviar 1 mensagem",now:Math.min(1,s.chat||0),target:1}]}
function award(info,amount,stat){if(!info?.name)return;const p=ensureProfile(info.name);p.xp+=amount;if(stat)p.stats[stat]=(p.stats[stat]||0)+1;p.level=levelFor(p.xp);send(info.ws,{type:"profile_state",profile:{...p,missions:missions(p)}});scheduleSave()}
function publicSong(s){return{id:s.id,title:s.title,url:s.url,videoId:s.videoId||youtubeId(s.url),requestedBy:s.requestedBy,votes:s.voters.size,priorityStatus:s.priorityStatus,priorityCode:s.priorityCode||"",createdAt:s.createdAt}}
function sortedMusic(){return[...musicQueue].sort((a,b)=>{const pa=a.priorityStatus==="paid"?1:0,pb=b.priorityStatus==="paid"?1:0;if(pb!==pa)return pb-pa;if(b.voters.size!==a.voters.size)return b.voters.size-a.voters.size;return a.createdAt-b.createdAt})}
function musicSnapshot(){return{current:currentSong?publicSong(currentSong):null,queue:sortedMusic().map(publicSong),config:{priorityPrice:PRIORITY_PRICE,paymentLink:PRIORITY_PAYMENT_LINK,manualApproval:true}}}
function leaderboardSnapshot(){const o={};for(const[k,v]of leaderboards)o[k]=v.map(x=>({...x}));return o}
function interactionSnapshot(){return JSON.parse(JSON.stringify(interactions))}
function stateSnapshot(){return{messages,leaderboards:Object.fromEntries([...leaderboards.entries()]),musicQueue:musicQueue.map(s=>({...s,voters:[...s.voters]})),currentSong:currentSong?{...currentSong,voters:[...currentSong.voters]}:null,interactions,profiles}}
function applyState(s){if(!s||typeof s!=="object")return;if(Array.isArray(s.messages))messages.splice(0,messages.length,...s.messages.slice(-MAX_HISTORY));if(s.leaderboards)for(const[k,v]of Object.entries(s.leaderboards))if(leaderboards.has(k)&&Array.isArray(v))leaderboards.set(k,v.slice(0,10));if(Array.isArray(s.musicQueue))musicQueue.splice(0,musicQueue.length,...s.musicQueue.map(x=>({...x,voters:new Set(Array.isArray(x.voters)?x.voters:[])})));if(s.currentSong)currentSong={...s.currentSong,voters:new Set(Array.isArray(s.currentSong.voters)?s.currentSong.voters:[])};if(s.interactions)Object.assign(interactions,s.interactions);if(s.profiles)Object.assign(profiles,s.profiles);interactions.lastEvents=(interactions.lastEvents||[]).slice(0,MAX_EVENTS)}
async function initPersistence(){try{if(fs.existsSync(STATE_FILE))applyState(JSON.parse(fs.readFileSync(STATE_FILE,"utf8")))}catch(e){console.error("local state load",e.message)}if(!DATABASE_URL)return;try{pool=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL.includes("localhost")?false:{rejectUnauthorized:false},max:3});await pool.query("CREATE TABLE IF NOT EXISTS lulu_state (id integer PRIMARY KEY,payload jsonb NOT NULL,updated_at timestamptz DEFAULT now())");await pool.query("CREATE TABLE IF NOT EXISTS lulu_events (id bigserial PRIMARY KEY,kind text NOT NULL,payload jsonb NOT NULL,created_at timestamptz DEFAULT now())");const r=await pool.query("SELECT payload FROM lulu_state WHERE id=1");if(r.rows[0]?.payload)applyState(r.rows[0].payload);dbReady=true;console.log("Postgres conectado")}catch(e){console.error("Postgres fallback local",e.message)}}
async function persist(){const s=stateSnapshot();try{fs.writeFileSync(STATE_FILE,JSON.stringify(s,null,2),"utf8")}catch(e){}if(pool&&dbReady)try{await pool.query("INSERT INTO lulu_state(id,payload,updated_at) VALUES(1,$1,now()) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=now()",[s])}catch(e){console.error("db save",e.message)}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(),180)}
function rememberEvent(kind,text,from="",icon="✨",tone="cyan",scene="spark"){const evt={id:crypto.randomUUID(),kind,text:clean(text,100),from:clean(from,30),icon,tone,scene,time:new Date().toISOString()};interactions.overlayEvents++;interactions.lastEvents.unshift(evt);interactions.lastEvents=interactions.lastEvents.slice(0,MAX_EVENTS);broadcast({type:"overlay_event",event:evt});broadcast({type:"interaction_state",interactions:interactionSnapshot()});scheduleSave();if(pool&&dbReady)pool.query("INSERT INTO lulu_events(kind,payload) VALUES($1,$2)",[kind,evt]).catch(()=>{});return evt}
function addLeaderboard(game,name,score){if(!leaderboards.has(game))return;score=Math.max(0,Math.min(1e6,Number(score)||0));name=safeName(name);const list=leaderboards.get(game),old=list.find(x=>x.name.toLowerCase()===name.toLowerCase());if(old)old.score=Math.max(old.score,score);else list.push({name,score});list.sort((a,b)=>b.score-a.score);list.splice(10);broadcast({type:"leaderboard_state",leaderboards:leaderboardSnapshot()});scheduleSave()}
function getRoom(n){if(!rooms.has(n))rooms.set(n,{name:n,active:true,winner:null,players:new Map(),resetTimer:null});return rooms.get(n)}
function roomSnapshot(n){const r=rooms.get(n);return r?{name:r.name,target:RACE_TARGET,active:r.active,winner:r.winner,players:[...r.players.entries()].map(([id,p])=>({id,name:p.name,score:p.score}))}:null}
function broadcastRoom(n){const r=roomSnapshot(n);if(r)broadcast({type:"race_state",room:r},i=>i.room===n)}
function removeRoom(i){if(!i.room)return;const r=rooms.get(i.room);if(r){r.players.delete(i.id);broadcastRoom(r.name);if(!r.players.size&&!r.resetTimer)rooms.delete(r.name)}i.room=null}
function resetRace(r){r.winner=null;r.active=true;for(const p of r.players.values())p.score=0;r.resetTimer=null;broadcastRoom(r.name)}
function authAdmin(info,token){if(!ADMIN_TOKEN)return false;const a=Buffer.from(clean(token,200).padEnd(ADMIN_TOKEN.length,"\0").slice(0,ADMIN_TOKEN.length)),b=Buffer.from(ADMIN_TOKEN);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function file(name){return fs.readFileSync(path.join(ROOT,name),"utf8")}
function injectPage(html,p){if((p==="/index.html"||p==="/community.html")&&!html.includes("id=\"v6-interact\""))html=html.replace(/<footer class="footer">/,file("v6-panel.html")+"<footer class=\"footer\">");if(p==="/index.html"||p==="/community.html")html=html.replace("</head>","<link rel=\"stylesheet\" href=\"/v6.css\"></head>").replace("</body>","<script src=\"/v6-inject.js\"></script></body>");if(p==="/studio.html")html=html.replace("</body>","<a href=\"/overlay.html?mode=horizontal\" target=\"_blank\" style=\"position:fixed;right:18px;bottom:18px;z-index:9999;padding:11px 14px;border-radius:12px;background:#087cff;color:white;text-decoration:none;font-weight:900\">Abrir Overlay EVO</a></body>");return html}
function proxy(req,res,htmlMode=false,pth=""){const pr=http.request({hostname:"127.0.0.1",port:ASSET_PORT,path:req.url,method:req.method,headers:{...req.headers,host:"127.0.0.1:"+ASSET_PORT}},ir=>{if(!htmlMode){res.writeHead(ir.statusCode||200,ir.headers);ir.pipe(res);return}const chunks=[];ir.on("data",c=>chunks.push(c));ir.on("end",()=>{let h=injectPage(Buffer.concat(chunks).toString("utf8"),pth);const headers={...ir.headers};delete headers["content-length"];headers["cache-control"]="no-cache";res.writeHead(ir.statusCode||200,headers);res.end(h)})});pr.on("error",()=>{res.writeHead(502);res.end("service unavailable")});req.pipe(pr)}
const server=http.createServer((req,res)=>{const u=new URL(req.url||"/","http://localhost"),p=u.pathname;if(p==="/health"){res.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify({ok:true,version:"6.0",online:clients.size,persistence:dbReady?"postgres":"local",interactions,music:musicSnapshot()}));return}if(p==="/community.js"||p==="/v6.css"||p==="/v6-inject.js"){const mime=p.endsWith(".css")?"text/css; charset=utf-8":"application/javascript; charset=utf-8";res.writeHead(200,{"Content-Type":mime,"Cache-Control":"no-cache"});res.end(file(p.slice(1)));return}if(p==="/overlay.html"){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache"});res.end(file("overlay-v6.html"));return}if(p==="/"||p.endsWith(".html"))return proxy(req,res,true,p==="/"?"/index.html":p);return proxy(req,res,false,p)});
const wss=new WebSocketServer({server,path:"/ws"});
wss.on("connection",(ws)=>{const info={id:crypto.randomUUID(),name:safeName(""),room:null,lastChat:0,lastMine:0,admin:false,pages:new Set(),countedVisit:false,ws};clients.set(ws,info);const pr=ensureProfile(info.name);send(ws,{type:"hello",online:clients.size,history:messages,you:{id:info.id,name:info.name},music:musicSnapshot(),leaderboards:leaderboardSnapshot(),interactions:interactionSnapshot(),profile:{...pr,missions:missions(pr)},adminAvailable:!!ADMIN_TOKEN});presence();ws.on("message",raw=>{let d;try{d=JSON.parse(raw.toString())}catch(e){return}if(!d||typeof d!=="object")return;
if(d.type==="set_name"){info.name=safeName(d.name);const p=ensureProfile(info.name);send(ws,{type:"profile_state",profile:{...p,missions:missions(p)}});return}
if(d.type==="track_page"){const page=clean(d.page,70)||"/";if(!info.countedVisit){interactions.visits++;info.countedVisit=true}if(!info.pages.has(page)){info.pages.add(page);interactions.pageViews[page]=(interactions.pageViews[page]||0)+1}broadcast({type:"interaction_state",interactions:interactionSnapshot()});scheduleSave();return}
if(d.type==="reaction"){const k=(clean(d.kind,20)||"hype").toLowerCase();if(!(k in interactions.reactions))interactions.reactions[k]=0;interactions.reactions[k]++;award(info,2,"reactions");const map={hype:["⚡","violet","hype"],heart:["💙","cyan","heart"],crown:["👑","gold","crown"],surprise:["✨","violet","surprise"]},m=map[k]||["✨","cyan","spark"];rememberEvent("reaction",k.toUpperCase()+" na Sociedade",info.name,m[0],m[1],m[2]);return}
if(d.type==="chat"){if(now()-info.lastChat<CHAT_INTERVAL)return;const t=clean(d.text,220);if(!t)return;info.lastChat=now();const item={id:crypto.randomUUID(),name:info.name,text:t,time:new Date().toISOString()};messages.push(item);while(messages.length>MAX_HISTORY)messages.shift();interactions.chatMessages++;award(info,3,"chat");broadcast({type:"chat",message:item});rememberEvent("chat",t.slice(0,75),info.name,"💬","cyan","surprise");return}
if(d.type==="leaderboard_submit"){const game=clean(d.game,20),score=Number(d.score)||0;if(leaderboards.has(game)){interactions.gamesPlayed++;award(info,5,"games");addLeaderboard(game,info.name,score);rememberEvent("score",game+" • "+score+" pts",info.name,"🏆","gold","score")}return}
if(d.type==="join_race"){const rn=(clean(d.room,20)||"principal").toLowerCase().replace(/[^a-z0-9_-]/g,"-");removeRoom(info);info.room=rn;const r=getRoom(rn);r.players.set(info.id,{name:info.name,score:0});interactions.gamesPlayed++;award(info,3,"games");broadcastRoom(rn);rememberEvent("race","entrou na corrida "+rn,info.name,"🏁","cyan","mining");return}
if(d.type==="leave_race"){removeRoom(info);return}
if(d.type==="mine"){if(!info.room||now()-info.lastMine<MINE_INTERVAL)return;info.lastMine=now();const r=rooms.get(info.room),p=r?.players.get(info.id);if(!r||!r.active||!p)return;p.score=Math.min(RACE_TARGET,p.score+1);if(p.score>=RACE_TARGET){r.active=false;r.winner=info.name;addLeaderboard("corrida",info.name,1);award(info,20,"wins");rememberEvent("winner","venceu a corrida "+r.name,info.name,"👑","gold","crown");broadcast({type:"race_winner",name:info.name,room:r.name},i=>i.room===r.name);r.resetTimer=setTimeout(()=>resetRace(r),5000)}broadcastRoom(r.name);return}
if(d.type==="music_add"){if(musicQueue.length>=MAX_MUSIC_QUEUE)return send(ws,{type:"error",message:"A fila está cheia."});const title=clean(d.title,90),url=clean(d.url,260),videoId=youtubeId(url);if(!title||!videoId)return send(ws,{type:"error",message:"Use um link válido do YouTube."});const pri=!!d.priorityRequested,s={id:crypto.randomUUID(),title,url,videoId,requestedBy:info.name,voters:new Set([info.id]),priorityStatus:pri?"pending":"none",priorityCode:pri?crypto.randomBytes(3).toString("hex").toUpperCase():"",createdAt:Date.now()};interactions.musicRequests++;award(info,4,"music");if(!currentSong)currentSong=s;else musicQueue.push(s);broadcast({type:"music_state",music:musicSnapshot()});rememberEvent("music",title,info.name,"♫",pri?"violet":"cyan","portal");send(ws,{type:"music_added",song:publicSong(s),priorityRequested:pri,startedNow:currentSong?.id===s.id,config:musicSnapshot().config});scheduleSave();return}
if(d.type==="music_vote"){const s=musicQueue.find(x=>x.id===clean(d.id,80));if(!s)return;if(s.voters.has(info.id))s.voters.delete(info.id);else{s.voters.add(info.id);interactions.musicVotes++;award(info,1,"votes");rememberEvent("vote","votou em "+s.title.slice(0,50),info.name,"🗳️","violet","spark")}broadcast({type:"music_state",music:musicSnapshot()});scheduleSave();return}
if(d.type==="admin_auth"){info.admin=authAdmin(info,d.token||"");send(ws,{type:"admin_status",ok:info.admin});return}
if(d.type==="music_admin"){if(!info.admin)return send(ws,{type:"error",message:"Ação restrita."});const a=clean(d.action,30),id=clean(d.id,80);if(a==="approve_priority"){const s=musicQueue.find(x=>x.id===id);if(s)s.priorityStatus="paid"}else if(a==="reject_priority"){const s=musicQueue.find(x=>x.id===id);if(s)s.priorityStatus="none"}else if(a==="remove"){const i=musicQueue.findIndex(x=>x.id===id);if(i>=0)musicQueue.splice(i,1)}else if(a==="play"){const i=musicQueue.findIndex(x=>x.id===id);if(i>=0)currentSong=musicQueue.splice(i,1)[0]}else if(a==="next"||a==="clear_current"){currentSong=null;const n=sortedMusic()[0];if(n){const i=musicQueue.findIndex(x=>x.id===n.id);currentSong=musicQueue.splice(i,1)[0]}}broadcast({type:"music_state",music:musicSnapshot()});scheduleSave();return}});
ws.on("close",()=>{removeRoom(info);clients.delete(ws);presence();scheduleSave()})});
initPersistence().finally(()=>server.listen(PORT,()=>console.log("LULUDAMOBILETE V6 backend",PORT,dbReady?"postgres":"local")));
