(function(){
'use strict';
var frame=document.getElementById('appFrame'),progress=document.getElementById('routeProgress'),radioBar=document.getElementById('radioBar'),radioTitle=document.getElementById('radioTitle'),radioMeta=document.getElementById('radioMeta'),onlineCount=document.getElementById('onlineCount'),soundState=document.getElementById('soundState'),muteButton=document.getElementById('muteButton'),toastEl=document.getElementById('shellToast'),palette=document.getElementById('palette'),paletteSearch=document.getElementById('paletteSearch'),paletteList=document.getElementById('paletteList');
var currentRoute='',suppressPush=false,ws=null,music={current:null,queue:[],config:{}},player=null,ytReady=false,pendingVideo='',currentVideo='',audioUnlocked=false,userMuted=false,volume=Number(localStorage.getItem('evoVolume')||72),metaTimer=null,reconnectTimer=null;
var commands=[['⌂','Início','Portal principal','/'],['♟','Sociedade','Comunidade Família EVO','/community.html'],['☵','Chat','Praça ao vivo','/community.html#chat'],['🎮','Arcade','Minigames Minecraft','/community.html#jogos'],['♫','Rádio EVO','Fila, votação e música','/community.html#radio'],['🏆','Ranking','Hall da Família EVO','/community.html#ranking'],['💙','Emotes','Emotes oficiais','/community.html#emotes']];
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(function(){toastEl.classList.remove('show')},2200)}
function rawRoute(){var p=location.pathname||'/';return p+location.search+location.hash}
function toView(route){var u=new URL(route,location.origin);var p=u.pathname==='/'?'/index.html':u.pathname;return '/__view'+p+u.search+u.hash}
function routeFromFrame(){try{var u=new URL(frame.contentWindow.location.href);var p=u.pathname.replace(/^\/__view/,'')||'/';if(p==='/index.html')p='/';return p+u.search+u.hash}catch(e){return currentRoute||'/'} }
function setLoading(on){document.body.classList.toggle('loading',!!on);if(!on){progress.style.width='100%';setTimeout(function(){progress.style.opacity='0';progress.style.width='0';setTimeout(function(){progress.style.opacity=''},250)},100)}}
function navigate(route,replace){var u=new URL(route,location.origin);if(u.pathname==='/overlay.html'){window.open(u.pathname+u.search+u.hash,'_blank');return}setLoading(true);currentRoute=u.pathname+u.search+u.hash;if(replace)history.replaceState({route:currentRoute},'',currentRoute);frame.src=toView(currentRoute)}
function syncHistory(){var route=routeFromFrame();if(!route)return;if(suppressPush){suppressPush=false;currentRoute=route;return}var here=rawRoute();if(route!==here){history.pushState({route:route},'',route);currentRoute=route}else currentRoute=route;updateMobile(route)}
function updateMobile(route){document.querySelectorAll('.mobileNav button').forEach(function(b){var r=b.getAttribute('data-route');b.classList.toggle('active',route===r||(r!=='/'&&route.indexOf(r.split('#')[0])===0&&(!r.includes('#')||route.indexOf(r.split('#')[1])>=0)))});}
function bindUserActivation(doc){['pointerdown','touchstart','keydown','click'].forEach(function(ev){doc.addEventListener(ev,unlockAudio,{capture:true,passive:true})});doc.addEventListener('keydown',shortcut,true)}
function enhanceFrame(){var d;try{d=frame.contentDocument}catch(e){return}if(!d)return;bindUserActivation(d);try{frame.contentWindow.addEventListener('hashchange',function(){var r=routeFromFrame();history.pushState({route:r},'',r);currentRoute=r;updateMobile(r)})}catch(e){}
 d.querySelectorAll('a[href*="studio.html"]').forEach(function(a){a.style.display='none'});
 var url=d.getElementById('musicUrl'),title=d.getElementById('musicTitle');if(url&&title&&!url.dataset.autoMeta){url.dataset.autoMeta='1';url.placeholder='Cole o link do YouTube — o nome será preenchido sozinho';var load=function(){clearTimeout(metaTimer);metaTimer=setTimeout(async function(){var v=url.value.trim();if(!v)return;try{var r=await fetch('/api/youtube-meta?url='+encodeURIComponent(v));var j=await r.json();if(j.ok&&j.title){title.value=j.title;title.dispatchEvent(new Event('input',{bubbles:true}));toast('♫ Música reconhecida: '+j.title)}}catch(e){}},450)};url.addEventListener('input',load);url.addEventListener('paste',function(){setTimeout(load,30)})}
 var art=d.getElementById('nowPlayingArt');if(art)art.style.pointerEvents='none';
 var tabs=d.querySelector('.gameTabs');if(tabs&&!tabs.querySelector('.evoRandomGame')){var b=d.createElement('button');b.type='button';b.className='gameTab evoRandomGame';b.textContent='🎲 Jogo aleatório';b.addEventListener('click',function(){var all=[].slice.call(tabs.querySelectorAll('.gameTab[data-game]'));if(!all.length)return;all[Math.floor(Math.random()*all.length)].click();tabs.scrollIntoView({behavior:'smooth',block:'start'})});tabs.appendChild(b)}
 d.querySelectorAll('a').forEach(function(a){try{var u=new URL(a.href,frame.contentWindow.location.href);if(u.pathname.indexOf('/__view/overlay.html')===0){a.addEventListener('click',function(e){e.preventDefault();window.open(u.pathname.replace('/__view','')+u.search+u.hash,'_blank')})}}catch(e){}})
}
frame.addEventListener('load',function(){setLoading(false);syncHistory();enhanceFrame();try{document.title=frame.contentDocument.title||'LULUDAMOBILETE'}catch(e){}});
window.addEventListener('popstate',function(){suppressPush=true;setLoading(true);frame.src=toView(rawRoute())});
document.querySelectorAll('[data-route]').forEach(function(b){b.addEventListener('click',function(){navigate(b.getAttribute('data-route'))})});
function shortcut(e){if((e.ctrlKey||e.metaKey)&&String(e.key).toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'&&!palette.hidden)closePalette()}
document.addEventListener('keydown',shortcut,true);bindUserActivation(document);document.getElementById('commandButton').addEventListener('click',openPalette);palette.addEventListener('click',function(e){if(e.target===palette)closePalette()});
function openPalette(){palette.hidden=false;paletteSearch.value='';renderCommands('');setTimeout(function(){paletteSearch.focus()},20)}function closePalette(){palette.hidden=true}
function renderCommands(q){q=String(q||'').toLowerCase();paletteList.innerHTML='';commands.filter(function(x){return (x[1]+' '+x[2]).toLowerCase().indexOf(q)>=0}).forEach(function(x){var b=document.createElement('button');b.className='paletteItem';b.innerHTML='<span>'+x[0]+' <b>'+x[1]+'</b><br><small>'+x[2]+'</small></span><small>abrir</small>';b.addEventListener('click',function(){closePalette();navigate(x[3])});paletteList.appendChild(b)})}paletteSearch.addEventListener('input',function(){renderCommands(this.value)});
function connect(){clearTimeout(reconnectTimer);var proto=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(proto+'//'+location.host+'/ws');ws.addEventListener('open',function(){ws.send(JSON.stringify({type:'set_name',name:localStorage.getItem('luluUserName')||'Ouvinte EVO'}))});ws.addEventListener('message',function(ev){var d;try{d=JSON.parse(ev.data)}catch(e){return}if(d.type==='hello'){onlineCount.textContent=(d.online||0)+' online';if(d.music)renderMusic(d.music)}else if(d.type==='presence')onlineCount.textContent=(d.online||0)+' online';else if(d.type==='music_state')renderMusic(d.music);else if(d.type==='music_added')toast(d.startedNow?'♫ Tocando agora: '+d.song.title:'♫ Música adicionada à fila')});ws.addEventListener('close',function(){onlineCount.textContent='reconectando';reconnectTimer=setTimeout(connect,1800)});ws.addEventListener('error',function(){})}
function videoId(url){var m=String(url||'').match(/(?:youtu\.be\/|(?:www\.|m\.|music\.)?youtube\.com\/(?:watch\?[^#]*v=|shorts\/|embed\/))([\w-]{6,})/i);return m?m[1]:''}
window.onYouTubeIframeAPIReady=function(){ytReady=true;if(pendingVideo)mountVideo(pendingVideo)};
function mountVideo(id){if(!id)return;pendingVideo=id;if(!ytReady||!window.YT||!YT.Player)return;currentVideo=id;document.getElementById('ytHost').innerHTML='<div id="evoYT"></div>';player=new YT.Player('evoYT',{width:'220',height:'180',videoId:id,playerVars:{autoplay:1,playsinline:1,rel:0,modestbranding:1},events:{onReady:function(e){soundState.textContent='tentando som automático';try{e.target.setVolume(volume);e.target.unMute();e.target.playVideo()}catch(x){}if(navigator.userActivation&&navigator.userActivation.hasBeenActive)unlockAudio()},onStateChange:function(e){radioBar.classList.toggle('playing',e.data===1);if(e.data===0&&music.current)nextSong(music.current.id);if(e.data===1&&audioUnlocked&&!userMuted){try{e.target.unMute();e.target.setVolume(volume)}catch(x){}}},onError:function(){soundState.textContent='pulando indisponível';if(music.current)setTimeout(function(){nextSong(music.current.id)},650)},onAutoplayBlocked:function(){try{player.mute();player.playVideo()}catch(x){}soundState.textContent='som no 1º toque'}}});try{player.getIframe().setAttribute('allow','autoplay; encrypted-media; picture-in-picture')}catch(e){}}
function unlockAudio(){if(userMuted)return;audioUnlocked=true;soundState.textContent='som automático';muteButton.textContent='🔊';if(player){try{player.unMute();player.setVolume(volume);player.playVideo()}catch(e){}}}
function renderMusic(m){music=m||{current:null,queue:[],config:{}};var c=music.current;if(c){radioTitle.textContent='♫ '+c.title;radioMeta.textContent='Pedido de '+c.requestedBy+' • '+(music.queue||[]).length+' na fila';var id=c.videoId||videoId(c.url);if(id&&id!==currentVideo)mountVideo(id)}else{radioTitle.textContent='♫ Rádio EVO';radioMeta.textContent=(music.queue||[]).length?'Escolhendo automaticamente a próxima música':'Aguardando pedido da Sociedade';radioBar.classList.remove('playing')}}
async function nextSong(id){try{await fetch('/api/radio/next',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id})})}catch(e){}}
muteButton.addEventListener('click',function(e){e.stopPropagation();userMuted=!userMuted;if(player){try{if(userMuted)player.mute();else{audioUnlocked=true;player.unMute();player.setVolume(volume);player.playVideo()}}catch(x){}}muteButton.textContent=userMuted?'🔇':'🔊';soundState.textContent=userMuted?'silenciado':'som automático'});
if(window.YT&&YT.Player){ytReady=true}connect();navigate(rawRoute(),true);renderCommands('');
})();